networks:
  dev:


services:
  frontend:
    build:
      context: ./frontend
      target: build
    volumes:
      - /app/node_modules
      - ./frontend/:/app
    container_name: frontend_application
    ports:
      - "5173:5173"
    networks:
      - dev

  backend:
    build:
      context: ./backend
    volumes:
      - /app/node_modules
      - ./backend/:/app
    container_name: backend_application
    ports:
      - "8081:8081"
    networks:
      - dev

  ngnix:
    image: nginx:stable-alpine
    ports:
      - 80:80
    volumes:
      - './nginx.conf:/etc/nginx/nginx.conf'
    depends_on:
      - backend
      - frontend
    networks:
      - dev
  db_sqlite:
    image: nouchka/sqlite3:latest
    stdin_open: true
    tty: true
    volumes:
      - ./backend/db/database/:/root/db/
    networks:
      - dev
    depends_on:
      - backend
      - frontend
