version: '1'

networks:
  dev:


services:
  frontend:
    build:
      context: frontend
    volumes:
      - /app/node_modules
      - ./frontend/:/app
    container_name: frontend_application
    networks:
      - dev

  backend:
    build:
      context: backend
    volumes:
      - /app/node_modules
      - ./backend/:/app
    container_name: backend_application
    networks:
      - dev

  ngnix:
    image: nginx:mainline
    ports:
      - 80:80
    volumes:
      - './nginx.conf:/etc/nginx/nginx.conf'
    depends_on:
      - backend
      - frontend
    networks:
      - dev
