version: '1'

services:
  frontend:
    build:
      context: frontend
    ports:
      - "5173:5173"
    volumes:
      - /app/node_modules
      - ./frontend/:/app
    container_name: frontend_application
  backend:
    build:
      context: backend
    ports:
      - '8081:8081'
    volumes:
      - /app/node_modules
      - ./backend/:/app
    container_name: backend_application
