networks:
  production:


services:
  frontend:
    build:
      context: ./frontend
      target: production
    restart: always
    volumes:
      - ./frontend/:/app
      - /app/node_modules
    container_name: frontend_production
    ports:
      - "5173:5173"
    networks:
      - production
    depends_on:
      - db_postgres

  backend:
    build:
      context: ./backend
      target: build
    restart: always
    environment:
      - PG_DB=dating
      - PG_USER=root
      - PG_PASSWORD=root
      - PG_HOST=db_postgres_production
    volumes:
      - ./backend/:/app
      - /app/node_modules/
    container_name: backend_production
    ports:
      - "8081:8081"
    networks:
      - production
    depends_on:
      - db_postgres

  ngnix:
    container_name: nginx-production
    image: nginx:stable-alpine
    restart: always
    ports:
      - 80:80
    volumes:
      - './nginx.conf:/etc/nginx/nginx.conf'
    depends_on:
      - backend
      - frontend
    networks:
      - production
  db_postgres:
    container_name: db_postgres_production
    image: postgres:16.4
    restart: always
    environment:
      - POSTGRES_DB=dating
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
    stdin_open: true
    tty: true
    networks:
      - production
    volumes:
      - db_postgres_data_production:/var/lib/postgresql/data

  adminer:
    container_name: adminer_production
    image: adminer
    restart: always
    ports:
      - 8080:8080
    networks:
      - production

volumes:
  db_postgres_data_production: {}
